=== EBIBioSamples/biosamples-v4/models/legacyxml/src/main/xsd/BioSD/BioSDSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- BioSamples API XML Schema - version v1.0 -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0"
	xmlns:tns="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0" elementFormDefault="qualified">

	<xs:simpleType name="stringValueType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:complexType name="annotationType">
		<xs:simpleContent>
			<xs:extension base="tns:stringValueType">
				<xs:attribute name="type" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="termSourceREFType">

		<xs:sequence>

			<xs:element name="Name" type="tns:stringValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Description" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="URI" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Version" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TermSourceID" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>

		</xs:sequence>

	</xs:complexType>

	<xs:complexType name="organizationType">

		<xs:sequence>

			<xs:element name="Name" type="tns:stringValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Address" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="URI" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Email" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Role" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>

		</xs:sequence>

	</xs:complexType>


	<xs:complexType name="databaseType">

		<xs:sequence>

			<xs:element name="Name" type="tns:stringValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ID" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="URI" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>

		</xs:sequence>

	</xs:complexType>

	<xs:complexType name="personType">

		<xs:sequence>

			<xs:element name="FirstName" type="tns:stringValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="LastName" type="tns:stringValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="MidInitials" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Email" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Role" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>

		</xs:sequence>

	</xs:complexType>

	<xs:complexType name="publicationType">

		<xs:sequence>

			<xs:element name="DOI" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PubMedID" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>

		</xs:sequence>

	</xs:complexType>

	<xs:complexType name="qualifiedValueType">
		<xs:sequence>
			<xs:element name="Value" type="tns:stringValueType" minOccurs="1" maxOccurs="1"/>				
			<xs:element name="TermSourceREF" type="tns:termSourceREFType" minOccurs="0"
				maxOccurs="1"/>		
			<xs:element name="Unit" type="tns:stringValueType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="propertyType">

		<xs:sequence>
			<xs:element name="QualifiedValue" type="tns:qualifiedValueType" minOccurs="0" maxOccurs="unbounded"/>

		</xs:sequence>


		<xs:attribute name="class" type="xs:string" use="required"/>

		<xs:attribute name="characteristic" type="xs:boolean" use="optional"/>
		<xs:attribute name="comment" type="xs:boolean" use="optional"/>

		<xs:attribute name="type" type="xs:string" use="optional"/>

	</xs:complexType>

	<xs:complexType name="GroupIdsType">
			<xs:sequence>
				<xs:element name="Id" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SampleIdsType">
		<xs:sequence>
			<xs:element name="Id" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<!--<xs:element name="idType" type="xs:string"/>-->


	
	<xs:complexType name="bioSampleGroupType">
		<xs:sequence>
			<xs:element name="Annotation" type="tns:annotationType" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="TermSource" type="tns:termSourceREFType" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="Property" type="tns:propertyType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Organization" type="tns:organizationType" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="Person" type="tns:personType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Database" type="tns:databaseType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Publication" type="tns:publicationType" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="SampleIds" type="tns:SampleIdsType" minOccurs="0"
				maxOccurs="1"/>
			<xs:element name="BioSample" type="tns:bioSampleType" minOccurs="0"
				maxOccurs="unbounded"/>
		</xs:sequence>

		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="bioSampleType">
		<xs:sequence>
			<xs:element name="Annotation" type="tns:annotationType" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="Property" type="tns:propertyType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="derivedFrom" type="tns:stringValueType" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="Database" type="tns:databaseType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="GroupIds" type="tns:GroupIdsType" minOccurs="0"
				maxOccurs="1"/>
		</xs:sequence>

		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="submissionCreateDate" type="xs:string" use="optional"/>
		<xs:attribute name="submissionSubmitDate" type="xs:string" use="optional"/>
		<xs:attribute name="submissionReleaseDate" type="xs:string" use="optional"/>
		<xs:attribute name="submissionUpdateDate" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:element name="BioSampleGroup" type="tns:bioSampleGroupType"/>

	<xs:element name="BioSample" type="tns:bioSampleType"/>

	<xs:element name="BioSamples">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BioSampleGroup" type="tns:bioSampleGroupType" minOccurs="0"
					maxOccurs="unbounded"/>
			</xs:sequence>

			<xs:attribute name="timestamp" type="xs:unsignedLong" use="optional"/>
		</xs:complexType>
	</xs:element>


</schema>

=== EBIBioSamples/biosamples-v4/integration/src/main/resources/SAMD00046940.xml
<BioSample
	xsi:schemaLocation="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0 http://www.ebi.ac.uk/biosamples/assets/xsd/v1.0/BioSDSchema.xsd"
	id="SAMD00046940" submissionUpdateDate="2017-04-07T21:57:22+00:00"
	submissionReleaseDate="2017-04-06T23:00:00+00:00"
	xmlns="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Property class="Sample Name" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>MiSeq, Diospyros lotus L8 male flower 23 Apr MeGI promoter
			</Value>
		</QualifiedValue>
	</Property>
	<Property class="Organism" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>Diospyros lotus</Value>
			<TermSourceREF>
				<Name />
				<TermSourceID>55363</TermSourceID>
			</TermSourceREF>
		</QualifiedValue>
	</Property>
	<Property class="Sex" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>male</Value>
			<TermSourceREF>
				<Name />
				<TermSourceID>http://purl.obolibrary.org/obo/PATO_0000384
				</TermSourceID>
			</TermSourceREF>
		</QualifiedValue>
	</Property>
	<Property class="colection date" characteristic="false"
		comment="false" type="STRING">
		<QualifiedValue>
			<Value>2014-04-23</Value>
		</QualifiedValue>
	</Property>
	<Property class="cultivar" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>KK-L8</Value>
		</QualifiedValue>
	</Property>
	<Property class="model" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>Generic</Value>
		</QualifiedValue>
	</Property>
	<Property class="organism part" characteristic="false"
		comment="false" type="STRING">
		<QualifiedValue>
			<Value>whole flower</Value>
		</QualifiedValue>
	</Property>
	<Property class="package" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>Generic.1.0</Value>
		</QualifiedValue>
	</Property>
	<Property class="synonym" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>TA_Meth-2</Value>
		</QualifiedValue>
	</Property>
	<Database>
		<Name>ENA</Name>
		<URI>http://www.ebi.ac.uk/ena/data/view/SAMD00046940</URI>
		<ID>SAMD00046940</ID>
	</Database>
</BioSample>

=== EBIBioSamples/biosamples-v4/integration/src/main/resources/SAMEG123.xml
<BioSampleGroup id="SAMEG123"
	xsi:schemaLocation="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0 http://www.ebi.ac.uk/biosamples/assets/xsd/v1.0/BioSDSchema.xsd"
	xmlns="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Property class="Submission Release Date" characteristic="false"
		type="DATETIME" comment="false">
		<QualifiedValue>
			<Value>2017-03-29T23:00:00+00:00</Value>
		</QualifiedValue>
	</Property>
	<Property class="Submission Update Date" characteristic="false"
		type="DATETIME" comment="false">
		<QualifiedValue>
			<Value>2017-04-22T21:24:51+00:00</Value>
		</QualifiedValue>
	</Property>
	<Property class="Submission Identifier" characteristic="false"
		type="STRING" comment="false">
		<QualifiedValue>
			<Value>TestLegacyXmlGroup</Value>
		</QualifiedValue>
	</Property>
	<Property class="Group Name" characteristic="true" type="STRING"
		comment="false">
		<QualifiedValue>
			<Value>SAMTSTXMLG1</Value>
		</QualifiedValue>
	</Property>
	<Database>
		<Name>other</Name>
		<URI>www.google.com</URI>
		<ID>www.google.com</ID>
	</Database>
	<SampleIds>
		<Id>SAME123456</Id>
		<Id>SAME78910</Id>
	</SampleIds>
</BioSampleGroup>

=== EBIBioSamples/biosamples-v4/integration/src/main/resources/SAMTSTXML1.xml
<BioSample
	xsi:schemaLocation="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0 http://www.ebi.ac.uk/biosamples/assets/xsd/v1.0/BioSDSchema.xsd"
	id="SAME12345679" submissionUpdateDate="2017-10-05T10:41:34.952+00:00"
	submissionReleaseDate="2016-04-01T11:36:57+00:00"
	xmlns="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Property class="Sample Name" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>TestLegacyXml</Value>
		</QualifiedValue>
	</Property>
	<Property class="Description" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>Test description</Value>
		</QualifiedValue>
	</Property>
	<Property class="Organism Part" characteristic="false"
		comment="false" type="STRING">
		<QualifiedValue>
			<Value>Lung</Value>
			<TermSourceREF>
				<Name />
				<TermSourceID>http://purl.obolibrary.org/obo/UBERON_0002048</TermSourceID>
			</TermSourceREF>
		</QualifiedValue>
	</Property>
	<Property class="Organism" characteristic="false"
			  comment="false" type="STRING">
		<QualifiedValue>
			<Value>Human</Value>
		</QualifiedValue>
	</Property>
	<Property class="test_Type" characteristic="false" comment="false"
		type="STRING">
		<QualifiedValue>
			<Value>test_value</Value>
		</QualifiedValue>
	</Property>
    <derivedFrom>SAMEA654195</derivedFrom>
	<Database>
		<Name>other</Name>
		<URI>www.google.com</URI>
		<ID>www.google.com</ID>
	</Database>
</BioSample>

=== EBIBioSamples/biosamples-v4/core/src/test/resources/core/TEST1.xml
<?xml version="1.0" encoding="UTF-8"?>
<BioSample xmlns="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0 http://www.ebi.ac.uk/biosamples/assets/xsd/v1.0/BioSDSchema.xsd"
           id="SAMEA1234" submissionCreateDate="2016-05-05T11:36:57+00:00"
           submissionUpdateDate="2016-05-05T11:36:57+00:00"
           submissionReleaseDate="2016-04-01T11:36:57+00:00"
           submissionSubmitDate="2016-04-01T11:36:57+00:00">
    <Property class="Sample Name" characteristic="false" comment="false"
              type="STRING">
        <QualifiedValue>
            <Value>Test Sample</Value>
        </QualifiedValue>
    </Property>
    <Property class="age" characteristic="false" comment="false"
              type="STRING">
        <QualifiedValue>
            <Value>3</Value>
            <Unit>year</Unit>
        </QualifiedValue>
    </Property>
    <Property class="organism" characteristic="false" comment="false"
              type="STRING">
        <QualifiedValue>
            <Value>Homo sapiens</Value>
            <TermSourceREF>
                <Name/>
                <TermSourceID>http://purl.obolibrary.org/obo/NCBITaxon_9606</TermSourceID>
            </TermSourceREF>
        </QualifiedValue>
    </Property>
    <Property class="organism part" characteristic="false"
              comment="false" type="STRING">
        <QualifiedValue>
            <Value>heart</Value>
        </QualifiedValue>
        <QualifiedValue>
            <Value>lung</Value>
        </QualifiedValue>
    </Property>
    <Property class="sex" characteristic="false" comment="false"
              type="STRING">
        <QualifiedValue>
            <Value>female</Value>
            <TermSourceREF>
                <Name/>
                <TermSourceID>http://purl.obolibrary.org/obo/PATO_0000383</TermSourceID>
            </TermSourceREF>
        </QualifiedValue>
    </Property>

    <derivedFrom>SAMD4321</derivedFrom>

    <Database>
        <Name>other</Name>
        <URI>http://www.google.com</URI>
    </Database>
</BioSample>
