=== EBIBioSamples/biosamples-v4/webapps/core/src/main/resources/schemas/core/sample.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"id": "https://www.ebi.ac.uk/biosamples/schemas/core/sample.json",
	"additionalProperties": false,
	"required": [
		"name",
		"domain",
		"release"
	],
	"type": "object",
	"definitions": {
		"characteristic": {
			"title": "BioSamples attribute",
			"description": "Metadata associated with a sample",
			"additionalProperties": false,
			"type": "object",
			"$ref": "#/character"
		},
		"contact": {
			"title": "Contact",
			"description": "Object representing a contact reference for the sample",
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"FirstName": {
					"type": "string"
				},
				"LastName": {
					"type": "string"
				},
				"MidInitials": {
					"type": "string"
				},
				"Name": {
					"type": "string"
				},
				"Role": {
					"type": "string"
				},
				"E-mail": {
					"type": "string"
				},
				"Affiliation": {
					"type": "string"
				},
				"URL": {
					"type": "string"
				}
			}
		},
		"external_reference": {
			"title": "BioSamples external reference",
			"description": "Object representing a link to a repository or page associated with the sample itself, e.g. a link to an ENA record ",
			"additionalProperties": false,
			"type": "object",
			"required": ["url"],
			"properties": {
				"url": {
					"type": "string"
				},
				"duo":{
					"description":"data use ontology",					
					"type":"array",
					"items":{
						"description":"Data use condition https://ega-archive.org/data-use-conditions",
						"type":"string",
						"pattern":"^DUO:[0-9]{7}$"
						}
					}
				}
			},
		"organisation": {
			"title": "Organisation",
			"description": "Object representing an organization related to the sample in some way",
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"Name": {
					"type": "string"
				},
				"Role": {
					"type": "string"
				},
				"E-mail": {
					"type": "string"
				},
				"URL": {
					"type": "string"
				},
				"Address": {
					"type": "string"
				}
			}
		},
		"publication": {
			"title": "Publication",
			"description": "Object representing a publication associated to the sample",
			"additionalProperties": false,
			"type": "object",
			"properties": {
				"doi": {
					"type": "string"
				},
				"pubmed_id": {
					"type": "string"
				}
			}
		},
		"relationship": {
			"title": "BioSamples relationship",
			"description": "Relationship object connecting two BioSamples accessions",
			"additionalProperties": false,
			"type": "object",
			"required": [
				"source",
				"type",
				"target"
			],
			"properties": {
				"source": {
					"description": "The sample accession where the relation starts from",
					"type": "string",
					"pattern": "^SAM(D|N|E([AG]?))[0-9]+$"
				},
				"type": {
					"type": "string"
				},
				"target": {
					"description": "The sample accession where the relation targets to",
					"type": "string",
					"pattern": "^SAM(D|N|E([AG]?))[0-9]+$"
				}
			}
		},
		"structured_data": {
			"title": "BioSamples structured data item",
			"description": "A structured data item, e.g. an antibiogram table",
			"additionalProperties": false,
			"required": [
				"type",
				"schema",
				"content"
			],
			"type": "object",
			"properties": {
				"type": {
					"description": "The type of structured data this item is",
					"type": "string",
					"enum": [
						"AMR"
					]
				},
				"schema": {
					"description": "The URL reference to the schema",
					"type": "string",
					"pattern": "(http|https)://www(dev)?.ebi.ac.uk/biosamples/schemas/structured/.*"
				},
				"content": {
					"type": [
						"array",
						"object"
					]
				}
			}
		}
	},
	"properties": {
		"name": {
			"description": "The sample name, or an alias, or another id",
			"type": "string"
		},
		"accession": {
			"description": "Sample accession",
			"type": "string",
			"pattern": "^SAM(D|N|E([AG]?))[0-9]+$"
		},
		"domain": {
			"description": "Sample AAP domain membership",
			"type": "string"
		},
		"release": {
			"description": "Sample relase date-time in ISO8601 format. Release date in the future means the sample is private",
			"type": "string",
			"format": "date-time"
		},
		"update": {
			"description": "Sample last update date-time in ISO8601 format. This is automatically set from the server on submission",
			"type": "string",
			"format": "date-time"
		},
		"taxId": {
			"description": "Sample NCBI taxonID.",
			"type": "integer"
				},
		"characteristics": {
			"description": "All the characteristics associated to the sample",
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/characteristic"
			}
		},
		"relationships": {
			"description": "Sample relationships with other samples in BioSamples",
			"type": "array",
			"items": {
				"$ref": "#/definitions/relationship"
			}
		},
		"externalReferences": {
			"description": "Array of references to external resources",
			"type": "array",
			"items": {
				"$ref": "#/definitions/external_reference"
			}
		},
		"organization": {
			"description": "Organization information associated with the sample",
			"type": "array",
			"items": {
				"$ref": "#/definitions/organisation"
			}
		},
		"contact": {
			"description": "Contact information of the people associated with the sample",
			"type": "array",
			"items": {
				"$ref": "#/definitions/contact"
			}
		},
		"publications": {
			"description": "Pubblications associated with the sample",
			"type": "array",
			"items": {
				"$ref": "#/definitions/publication"
			}
		},
		"data": {
			"description": "Contains the structured data associated with a sample",
			"type": "array",
			"items": {
				"$ref": "#/definitions/structured_data"
			}
		}
	},
	"character": {
		"type": "array",
		"properties": {
			"text": {
				"description": "The attribute value expressed as text",
				"type": "string"
			},
			"ontologyTerms": {
				"description": "An array of ontology iri associated to the attribute value",
				"type": "array",
				"items": {
					"type": "string"
				}
			},
			"unit": {
				"description": "The unit associated with the attribute value",
				"type": "string"
			}
		}
	}
}

=== EBIBioSamples/biosamples-v4/webapps/core/src/test/resources/amr_sample.json
{
  "name": "testSample",
  "domain": "foozit",
  "update": "2018-07-18T10:01:23Z",
  "release": "2018-07-18T10:01:23Z",
  "data": [{
    "type": "AMR",
    "schema": "test",
    "content": [
      {
        "antibiotic_name":"ampicillin",
        "resistance_phenotype":"susceptible",
        "measurement_sign":"==",
        "measurement": "2",
        "measurement_units":"mg/L",
        "vendor":"in-house",
        "laboratory_typing_method":"MIC",
        "ast_standard":"CLSI"
      }
    ]
  }]
}
